/pointcloud_to_laserscan:
  ros__parameters:
    angle_increment: 0.0087
    angle_max: 3.1417
    angle_min: -3.1417
    inf_epsilon: 1.0
    max_height: 3.0
    min_height: 0.0
    qos_overrides:
      /parameter_events:
        publisher:
          depth: 1000
          reliability: best_effort
    queue_size: 16
    range_max: 20.0
    range_min: 0.35
    scan_time: 0.1
    target_frame: base_link
    transform_tolerance: 0.01
    use_inf: true
    use_sim_time: true