<?xml version="1.0"?>
<robot name="bot" xmlns:xacro="http://ros.org/wiki/xacro">

  <xacro:property name="base_length" value="0.400" />
  <xacro:property name="base_width" value="0.200" />
  <xacro:property name="base_height" value="0.129" />
  <xacro:property name="base_mass" value="10" />

  <xacro:property name="wheel_radius" value="0.07162" />
  <xacro:property name="wheel_width" value="0.05" />
  <xacro:property name="wheel_pos_x" value="0.120" />
  <xacro:property name="wheel_pos_y" value="0.1355" />
  <xacro:property name="wheel_pos_z" value="-0.04788" />
  <xacro:property name="wheel_mass" value=".6" />
  <xacro:property name="wheel_torque" value="20" />


  <xacro:include filename="$(find bot_description)/urdf/parts_urdf/base.urdf.xacro" />
  <xacro:include filename="$(find bot_description)/urdf/parts_urdf/wheel.urdf.xacro" />
  <xacro:include filename="$(find bot_description)/urdf/sensors/imu.urdf.xacro" />
  <xacro:include filename="$(find bot_description)/urdf/sensors/laser.urdf.xacro" />
  <xacro:include filename="$(find bot_description)/urdf/drivers/differential_drive.urdf.xacro" />

  <xacro:base 
    length="${base_length}" 
    width="${base_width}" 
    height="${base_height}" 
    mass="${base_mass}"
    wheel_radius="${wheel_radius}"
    wheel_pos_z="${wheel_pos_z}"
/>

  <xacro:wheel 
    side="front_left"
    radius="${wheel_radius}" 
    width="${wheel_width}" 
    pos_x="${wheel_pos_x}" 
    pos_y="${wheel_pos_y}" 
    pos_z="${wheel_pos_z}" 
    mass="${wheel_mass}"
  />

  <xacro:wheel 
    side="front_right"
    radius="${wheel_radius}" 
    width="${wheel_width}" 
    pos_x="${wheel_pos_x}" 
    pos_y="${-wheel_pos_y}" 
    pos_z="${wheel_pos_z}" 
    mass="${wheel_mass}"
  />
  <xacro:wheel 
    side="rear_left"
    radius="${wheel_radius}" 
    width="${wheel_width}" 
    pos_x="${-wheel_pos_x}" 
    pos_y="${wheel_pos_y}" 
    pos_z="${wheel_pos_z}" 
    mass="${wheel_mass}"
  />

  <xacro:wheel 
    side="rear_right"
    radius="${wheel_radius}" 
    width="${wheel_width}" 
    pos_x="${-wheel_pos_x}" 
    pos_y="${-wheel_pos_y}" 
    pos_z="${wheel_pos_z}" 
    mass="${wheel_mass}"
  />

  <xacro:imu/>
  
  <xacro:laser/>

  <xacro:diff_drive_controller
    wheel_separation="${wheel_pos_y * 2}"
    wheel_radius="${wheel_radius}"
    wheel_torque="${wheel_torque}"
  />
</robot>